[package]
name = "tooling-rs"
version = "0.1.0"
authors = ["Matthieu Pizenberg <matthieu.pizenberg@gmail.com>"]
edition = "2018"

[dependencies]
visual-odometry-rs = { path = "/home/matthieu/git/phd/slam/visual-odometry-rs"}
nalgebra = "0.17"
